Add FAQ A4 on use of KBV
usnistgov/800-63-FAQ pull request #15
Opened 2019-10-16 19:23 UTC by jimfenton

2019-10-17 19:53 UTC, jricher commented
The wording of this buries the takeaway that KBV can't be used at these levels. I would suggest leading with the statement "KBV cannot be used at IAL2 or IAL3", then keeping the rest as an explanation of the statement.

2019-10-17 19:53 UTC, jricher requested changes
The wording of this buries the takeaway that KBV can't be used at these levels. I would suggest leading with the statement "KBV cannot be used at IAL2 or IAL3", then keeping the rest as an explanation of the statement.

2019-10-18 22:01 UTC, jimfenton commented
Yes, I guess I did bury the lede a bit here. I'll work on that.

2019-10-21 15:07 UTC, jricher approved these changes

2020-01-07 15:15 UTC, DTemo approved these changes

2020-01-07 20:18 UTC, merged