added faq on procured requirement
usnistgov/800-63-FAQ pull request #23
Opened 2020-07-02 20:02 UTC by jricher

Addresses usnistgov/800-63-3#1970

2020-07-02 20:25 UTC, jimfenton requested changes

2020-07-02 20:25 UTC, jimfenton commented on _63B/procured.md
> +title: What process does "procured" refer to when talking about authenticators?
```suggestion
title: When do FIPS 140 requirements apply to authenticators used at AAL2?
```

2020-07-02 20:25 UTC, jimfenton commented on _63B/procured.md
> +[800-63B section 4.2.2](https://pages.nist.gov/800-63-3/sp800-63b.html#aal2req) states that "Authenticators _procured by_ government agencies SHALL be validated to meet the requirements of FIPS 140 L
```suggestion
[800-63B section 4.2.2](https://pages.nist.gov/800-63-3/sp800-63b.html#aal2req) states that "Authenticators _procured by_ government agencies SHALL be validated to meet the requirements of FIPS 140 Level 1." (emphasis added) The intent of the _procured by_ language is to exempt user-provided ("bring-your-own") authenticators from having to meet FIPS 140 requirements, particularly in the government-to-public use case. The FIPS 140 requirement applies only to authenticators purchased or issued by a government agency.
```

2020-07-02 20:29 UTC, jimfenton approved these changes

2020-07-05 20:52 UTC, DTemo approved these changes

2020-07-05 21:14 UTC, merged